name: wuchuheng_hooks
description: Hooks is a state management library where data can be set and changes can be subscribed.
version: 0.0.9
homepage: https://github.com/wuchuheng/hooks_dart

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  uuid: ^3.0.6
